# Generated by Django 3.0.8 on 2021-02-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOAN_ID', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ed', models.IntegerField(blank=True, null=True)),
                ('employ', models.IntegerField(blank=True, null=True)),
                ('address', models.IntegerField(blank=True, null=True)),
                ('income', models.FloatField(blank=True, null=True)),
                ('debtinc', models.FloatField(blank=True, null=True)),
                ('creddebt', models.FloatField(blank=True, null=True)),
                ('othdebt', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
